version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run

orbs:
  hello-orb: xavidop/circleci-orb-hello-world@0.0.1

commands:
  # A command named `echo` that runs the `echo` command
  echo:
    parameters:
      message:
        type: string
        default: "hello world"
    steps:
      - run: echo << parameters.message >>

jobs:
  hello-job:
    executor: node # use the `node` executor defined above
    steps:
      - checkout # check out the code in the project directory
      - echo # run the `echo` command

  hello-job-setter:
    executor: node # use the `node` executor defined above
    steps:
      - run: echo "hello world" > hello.txt
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - ./

  hello-job-getter:
    executor: node # use the `node` executor defined above
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: .
      - run: |
          if [[ `cat hello.txt` == "hello world" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  my-workflow:
    jobs:
      - hello-job
      - hello-orb/hello
      - hello-job-setter
      - hello-job-getter:
          requires:
            - hello-job-setter